// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVe6UnHXrnX5EX3z3te_mo4tIcjukmT40',
    appId: '1:814226413180:web:14a2f65512efe5b39f9bf9',
    messagingSenderId: '814226413180',
    projectId: 'auth-codelabs',
    authDomain: 'auth-codelabs.firebaseapp.com',
    storageBucket: 'auth-codelabs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOEAmhJNbYAQNlQisruKR9jq_pauZHNT0',
    appId: '1:814226413180:android:4472a1b0b283e7339f9bf9',
    messagingSenderId: '814226413180',
    projectId: 'auth-codelabs',
    storageBucket: 'auth-codelabs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKRVoKM8001UJGPspOqqpYPj_YbbkulAA',
    appId: '1:814226413180:ios:dfd18814f18177399f9bf9',
    messagingSenderId: '814226413180',
    projectId: 'auth-codelabs',
    storageBucket: 'auth-codelabs.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKRVoKM8001UJGPspOqqpYPj_YbbkulAA',
    appId: '1:814226413180:ios:dfd18814f18177399f9bf9',
    messagingSenderId: '814226413180',
    projectId: 'auth-codelabs',
    storageBucket: 'auth-codelabs.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
